### PR TITLE
[WIP] Add Windows executable

### PR DESCRIPTION
**Pull request by AnshulMalik**
Added usage with command line arguments.

Doing experimentation with spawning child process.

### CODE REVIEW

**Comment by TheJaredWilcurt** [comment]
@AnshulMalik 

Hey, I pushed a big update that reorganizes the code and makes it a little cleaner. Can you pull latest and update your PR?

Currently the `identify` method seems to be fully functional. I was going to work on decode next since encode has a lot more advanced options and transcode is just going to be a combination of those other two.

You can look at how `identify` is structures in `index.js` and how it's documented in the README to get an idea of how I'm planning the other ones.

**Comment by AnshulMalik** [comment]
Great !

Let me know what part you'd like to see me working.

I am having some issues with LF and CRLF.

**Comment by TheJaredWilcurt** [comment]
So I just looked into `command-line-args` which I hadn't used before. It looks like this lets you create a JS file that acts like a CLI. I don't really think that's needed for this project as we will be shipping the actual CLI with the module. So if people want to they could just add `node-flif` as a dependency and then just run the CLI themselves from the `node_modules/node-flif/executables/OSARCH/flif`.

I've pushed another update that I think will fix the CRLF stuff.

You can do the breakpoints thing. It's basically the same idea as identify. just look at the README API for it and try to make it do that. Use `identify` as a reference.

**Comment by AnshulMalik** [comment]
Wasn't clear about the goals at that time. 

Also, have exams so can't do much work. It'll be easier of someone can add a binary for linux.

**Comment by TheJaredWilcurt** [comment]
@AnshulMalik 

I've added Linux builds of the `flif` executable to the repo and split the code up into individual modules.

**Comment by TheJaredWilcurt** [comment]
I've updated the repo to use `flif-wasm` as the executable for non-windows systems, and for Windows I've done my own build and included all required files so it should work on any Win 32/64 machine. Closing this PR.

**Pull request closed without merging**
